// Package message はAPIレスポンス用のエラーコード・メッセージコード定数と構造体。
package message

const (
	AccountInvalidLoginRequestDataError                              = "ERR000001"
	AccountNotFoundError                                             = "ERR000002"
	AccountIsNotEnableError                                          = "ERR000003"
	AccountPasswordResetTokenIsNotNilError                           = "ERR000004"
	AccountInvalidPasswordError                                      = "ERR000005"
	AccountLoginInternalServerError                                  = "ERR000006"
	AccountInvalidLoginResponseDataError                             = "ERR000007"
	AccountInvalidLogoutRequestDataError                             = "ERR000008"
	AccountInvalidLogoutResponseDataError                            = "ERR000009"
	AccountLogoutInternalServerError                                 = "ERR000010"
	AccountInvalidResetPasswordResponseDataError                     = "ERR000011"
	AccountInvalidResetPasswordRequestDataError                      = "ERR000012"
	AccountSessionNotFoundError                                      = "ERR000013"
	AccountNotHasAdminError                                          = "ERR000014"
	AccountInfoUpdateError                                           = "ERR000015"
	AccountInvalidSetNewPasswordRequestDataError                     = "ERR000016"
	AccountInvalidSetNewPasswordResponseDataError                    = "ERR000017"
	RepositoriesGetError                                             = "ERR000018"
	AddTagError                                                      = "ERR000019"
	GetTagError                                                      = "ERR000020"
	AddTextError                                                     = "ERR000021"
	GetTextError                                                     = "ERR000022"
	AddKmemoError                                                    = "ERR000023"
	GetKmemoError                                                    = "ERR000024"
	InvalidAddTagRequestDataError                                    = "ERR000025"
	InvalidAddTagResponseDataError                                   = "ERR000026"
	InvalidAddTextRequestDataError                                   = "ERR000027"
	InvalidAddTextResponseDataError                                  = "ERR000028"
	AddURLogError                                                    = "ERR000029"
	GetURLogError                                                    = "ERR000030"
	InvalidAddURLogRequestDataError                                  = "ERR000031"
	InvalidAddURLogResponseDataError                                 = "ERR000032"
	AddNlogError                                                     = "ERR000033"
	GetNlogError                                                     = "ERR000034"
	InvalidAddNlogRequestDataError                                   = "ERR000035"
	InvalidAddNlogResponseDataError                                  = "ERR000036"
	AddTimeIsError                                                   = "ERR000037"
	GetTimeIsError                                                   = "ERR000038"
	InvalidAddTimeIsRequestDataError                                 = "ERR000039"
	InvalidAddTimeIsResponseDataError                                = "ERR000040"
	AddLantanaError                                                  = "ERR000041"
	GetLantanaError                                                  = "ERR000042"
	InvalidAddLantanaRequestDataError                                = "ERR000043"
	InvalidAddLantanaResponseDataError                               = "ERR000044"
	AddKyouInfoError                                                 = "ERR000045"
	GetKyouInfoError                                                 = "ERR000046"
	InvalidAddKyouInfoRequestDataError                               = "ERR000047"
	InvalidAddKyouInfoResponseDataError                              = "ERR000048"
	AddReKyouError                                                   = "ERR000049"
	GetReKyouError                                                   = "ERR000050"
	InvalidAddReKyouRequestDataError                                 = "ERR000051"
	InvalidAddReKyouResponseDataError                                = "ERR000052"
	InvalidUpdateTagRequestDataError                                 = "ERR000053"
	InvalidUpdateTagResponseDataError                                = "ERR000054"
	NotFoundTagError                                                 = "ERR000055"
	AlreadyExistTagError                                             = "ERR000056"
	AlreadyExistTextError                                            = "ERR000057"
	AlreadyExistKmemoError                                           = "ERR000058"
	AlreadyExistURLogError                                           = "ERR000059"
	AlreadyExistNlogError                                            = "ERR000060"
	AlreadyExistTimeIsError                                          = "ERR000061"
	AlreadyExistLantanaError                                         = "ERR000062"
	AlreadyExistKyouInfoError                                        = "ERR000063"
	AlreadyExistReKyouError                                          = "ERR000064"
	InvalidUpdateTextRequestDataError                                = "ERR000065"
	InvalidUpdateTextResponseDataError                               = "ERR000066"
	NotFoundTextError                                                = "ERR000067"
	InvalidUpdateKmemoRequestDataError                               = "ERR000068"
	InvalidUpdateKmemoResponseDataError                              = "ERR000069"
	NotFoundKmemoError                                               = "ERR000070"
	InvalidUpdateURLogRequestDataError                               = "ERR000071"
	InvalidUpdateURLogResponseDataError                              = "ERR000072"
	NotFoundURLogError                                               = "ERR000073"
	InvalidUpdateNlogRequestDataError                                = "ERR000074"
	InvalidUpdateNlogResponseDataError                               = "ERR000075"
	NotFoundNlogError                                                = "ERR000076"
	InvalidUpdateTimeIsRequestDataError                              = "ERR000077"
	InvalidUpdateTimeIsResponseDataError                             = "ERR000078"
	NotFoundTimeIsError                                              = "ERR000079"
	InvalidUpdateLantanaRequestDataError                             = "ERR000080"
	InvalidUpdateLantanaResponseDataError                            = "ERR000081"
	NotFoundLantanaError                                             = "ERR000082"
	AddMiError                                                       = "ERR000083"
	GetMiError                                                       = "ERR000084"
	InvalidAddMiRequestDataError                                     = "ERR000085"
	InvalidAddMiResponseDataError                                    = "ERR000086"
	AlreadyExistMiError                                              = "ERR000087"
	InvalidUpdateMiRequestDataError                                  = "ERR000088"
	InvalidUpdateMiResponseDataError                                 = "ERR000358"
	NotFoundMiError                                                  = "ERR000089"
	InvalidUpdateKyouInfoRequestDataError                            = "ERR000090"
	InvalidUpdateKyouInfoResponseDataError                           = "ERR000091"
	NotFoundKyouInfoError                                            = "ERR000092"
	InvalidUpdateReKyouRequestDataError                              = "ERR000093"
	InvalidUpdateReKyouResponseDataError                             = "ERR000094"
	NotFoundReKyouError                                              = "ERR000095"
	AccountInvalidAddKmemoResponseDataError                          = "ERR000096"
	AccountInvalidAddKmemoRequestDataError                           = "ERR000097"
	InvalidGetKyousResponseDataError                                 = "ERR000098"
	InvalidGetKyousRequestDataError                                  = "ERR000099"
	InvalidGetKyouResponseDataError                                  = "ERR000359"
	InvalidGetKyouRequestDataError                                   = "ERR000100"
	GetKyouError                                                     = "ERR000101"
	InvalidGetKmemoResponseDataError                                 = "ERR000102"
	InvalidGetKmemoRequestDataError                                  = "ERR000103"
	InvalidGetURLogResponseDataError                                 = "ERR000104"
	InvalidGetURLogRequestDataError                                  = "ERR000105"
	InvalidGetNlogResponseDataError                                  = "ERR000106"
	InvalidGetNlogRequestDataError                                   = "ERR000107"
	InvalidGetTimeIsResponseDataError                                = "ERR000108"
	InvalidGetTimeIsRequestDataError                                 = "ERR000109"
	InvalidGetMiResponseDataError                                    = "ERR000110"
	InvalidGetMiRequestDataError                                     = "ERR000111"
	InvalidGetLantanaResponseDataError                               = "ERR000112"
	InvalidGetLantanaRequestDataError                                = "ERR000113"
	InvalidGetReKyouResponseDataError                                = "ERR000114"
	InvalidGetReKyouRequestDataError                                 = "ERR000115"
	InvalidGetGitCommitLogResponseDataError                          = "ERR000116"
	InvalidGetGitCommitLogRequestDataError                           = "ERR000117"
	GetGitCommitLogError                                             = "ERR000118"
	InvalidGetMiBoardNamesResponseDataError                          = "ERR000122"
	InvalidGetMiBoardNamesRequestDataError                           = "ERR000123"
	GetMiBoardNamesError                                             = "ERR000124"
	InvalidGetAllTagNamesResponseDataError                           = "ERR000125"
	InvalidGetAllTagNamesRequestDataError                            = "ERR000126"
	GetAllTagNamesError                                              = "ERR000127"
	InvalidGetTagsByTargetIDResponseDataError                        = "ERR000128"
	InvalidGetTagsByTargetIDRequestDataError                         = "ERR000129"
	GetTagsByTargetIDError                                           = "ERR000130"
	InvalidGetTagHistoriesByTagIDResponseDataError                   = "ERR000131"
	InvalidGetTagHistoriesByTagIDRequestDataError                    = "ERR000132"
	GetTagHistoriesByTagIDError                                      = "ERR000133"
	InvalidGetTextHistoriesByTextIDResponseDataError                 = "ERR000134"
	InvalidGetTextHistoriesByTextIDRequestDataError                  = "ERR000135"
	GetTextHistoriesByTextIDError                                    = "ERR000136"
	InvalidGetTextsByTargetIDResponseDataError                       = "ERR000137"
	InvalidGetTextsByTargetIDRequestDataError                        = "ERR000138"
	GetTextsByTargetIDError                                          = "ERR000139"
	InvalidGetApplicationConfigResponseDataError                     = "ERR000140"
	InvalidGetApplicationConfigRequestDataError                      = "ERR000141"
	GetApplicationConfigError                                        = "ERR000142"
	InvalidGetServerConfigResponseDataError                          = "ERR000143"
	InvalidGetServerConfigRequestDataError                           = "ERR000144"
	GetServerConfigError                                             = "ERR000145"
	InvalidUploadFilesResponseDataError                              = "ERR000146"
	InvalidUploadFilesRequestDataError                               = "ERR000147"
	InvalidUploadGPSLogFilesResponseDataError                        = "ERR000148"
	InvalidUploadGPSLogFilesRequestDataError                         = "ERR000149"
	InvalidStatusGetRepNameError                                     = "ERR000150"
	NotFoundTargetIDFRepError                                        = "ERR000151"
	GetRepPathError                                                  = "ERR000152"
	NotFoundTargetGPSLogRepError                                     = "ERR000153"
	ConvertGPSLogError                                               = "ERR000154"
	GenerateGPXFileContentError                                      = "ERR000155"
	WriteGPXFileError                                                = "ERR000156"
	NotImplementsError                                               = "ERR000157"
	InvalidUpdateAccountStatusResponseDataError                      = "ERR000178"
	InvalidUpdateAccountStatusRequestDataError                       = "ERR000179"
	UpdateUsersAccountStatusError                                    = "ERR000180"
	InvalidUpdateUserRepsResponseDataError                           = "ERR000181"
	InvalidUpdateUserRepsRequestDataError                            = "ERR000182"
	DeleteAllRepositoriesByUserError                                 = "ERR000183"
	AccountInvalidAddAccountResponseDataError                        = "ERR000184"
	AccountInvalidAddAccountRequestDataError                         = "ERR000185"
	GetAccountError                                                  = "ERR000186"
	AlreadyExistAccountError                                         = "ERR000187"
	AddAccountError                                                  = "ERR000188"
	InvalidGetGPSLogResponseDataError                                = "ERR000189"
	InvalidGetGPSLogRequestDataError                                 = "ERR000190"
	GetGPSLogError                                                   = "ERR000191"
	InvalidGetShareKyouListInfosResponseDataError                    = "ERR000194"
	InvalidGetShareKyouListInfosRequestDataError                     = "ERR000195"
	GetShareKyouListInfosError                                       = "ERR000196"
	InvalidDeleteShareKyouListInfosResponseDataError                 = "ERR000197"
	InvalidDeleteShareKyouListInfosRequestDataError                  = "ERR000198"
	DeleteShareKyouListInfosError                                    = "ERR000199"
	InvalidGetMiSharedTasksResponseDataError                         = "ERR000200"
	InvalidGetMiSharedTasksRequestDataError                          = "ERR000201"
	GetMiSharedTasksError                                            = "ERR000202"
	FindMiKyousError                                                 = "ERR000203"
	InvalidAddShareKyouListInfoResponseDataError                     = "ERR000211"
	InvalidAddShareKyouListInfoRequestDataError                      = "ERR000212"
	GetShareKyouListInfoError                                        = "ERR000213"
	AlreadyExistShareKyouListInfoError                               = "ERR000214"
	AddShareKyouListInfoError                                        = "ERR000215"
	AccountInvalidGenerateTLSFileResponseDataError                   = "ERR000216"
	AccountInvalidGenerateTLSFileRequestDataError                    = "ERR000217"
	GetTLSFileNamesError                                             = "ERR000218"
	GenerateTLSFilesError                                            = "ERR000219"
	GetDeviceError                                                   = "ERR000220"
	RemoveCertFileError                                              = "ERR000221"
	RemovePemFileError                                               = "ERR000222"
	GetIDFKyouError                                                  = "ERR000223"
	InvalidUpdateApplicationconfigResponseDataError                  = "ERR000224"
	InvalidUpdateApplicationConfigRequestDataError                   = "ERR000225"
	UpdateApplicationConfigError                                     = "ERR000226"
	InvalidUpdateServerConfigResponseDataError                       = "ERR000232"
	InvalidUpdateServerConfigRequestDataError                        = "ERR000233"
	UpdateServerConfigError                                          = "ERR000234"
	GetAllAccountConfigError                                         = "ERR000235"
	GetAllRepositoriesError                                          = "ERR000236"
	AddApplicationConfig                                             = "ERR000237"
	AccountDisabledError                                             = "ERR000238"
	InvalidGetMiSharedTaskRequest                                    = "ERR000239"
	InvalidGetRepositoriesResponseDataError                          = "ERR000240"
	InvalidGetRepositoriesRequestDataError                           = "ERR000241"
	GetRepositoriesError                                             = "ERR000242"
	InvalidGetAllRepNamesRequestDataError                            = "ERR000244"
	GetAllRepNamesError                                              = "ERR000245"
	InvalidGetAllRepNamesResponseDataError                           = "ERR000246"
	InvalidPasswordResetTokenError                                   = "ERR000247"
	InvalidGetIDFKyouResponseDataError                               = "ERR000248"
	InvalidGetIDFKyouRequestDataError                                = "ERR000249"
	AddUpdatedRepositoriesByUser                                     = "ERR000250"
	InvalidUpdateIDFKyouResponseDataError                            = "ERR000251"
	InvalidUpdateIDFKyouRequestDataError                             = "ERR000252"
	AddIDFKyouError                                                  = "ERR000253"
	NotFoundIDFKyouError                                             = "ERR000254"
	FailedMarshalJSONFindQuery                                       = "ERR000255"
	InvalidUpdateShareKyouListInfoResponseDataError                  = "ERR000256"
	InvalidUpdateShareKyouListInfoRequestDataError                   = "ERR000257"
	UpdateShareKyouListInfoError                                     = "ERR000258"
	NotExistShareKyouListInfoError                                   = "ERR000259"
	FindKyousShareKyouError                                          = "ERR000260"
	FindMisShareKyouError                                            = "ERR000261"
	FindTagsShareKyouError                                           = "ERR000262"
	FindTextsShareKyouError                                          = "ERR000263"
	InvalidGetPlayingKyousResponseDataError                          = "ERR000264"
	InvalidGetPlayingTimeIsRequestDataError                          = "ERR000265"
	FindKyousPlayingTimeIsError                                      = "ERR000266"
	InvalidGetMiTaskNotificationPublicKeyResponseDataError           = "ERR000267"
	InvalidGetMiTaskNotificationPublicKeyRequestDataError            = "ERR000268"
	InvalidRegisterMiTaskNotificationResponse                        = "ERR000269"
	InvalidRegisterMiTaskNotificationRequest                         = "ERR000270"
	GenerateVAPIDKeysError                                           = "ERR000271"
	AddGkillNotificationTargetError                                  = "ERR000272"
	InvalidAddNotificationResponseDataError                          = "ERR000273"
	InvalidAddNotificationRequestDataError                           = "ERR000274"
	GetNotificationError                                             = "ERR000275"
	AlreadyExistNotificationError                                    = "ERR000276"
	AddNotificationError                                             = "ERR000277"
	InvalidUpdateNotificationResponseDataError                       = "ERR000278"
	InvalidUpdateNotificationRequestDataError                        = "ERR000279"
	NotFoundNotificationError                                        = "ERR000280"
	UpdateNotificationSuccessMessage                                 = "ERR000281"
	InvalidGetNotificationsByTargetIDResponseDataError               = "ERR000282"
	InvalidGetNotificationsByTargetIDRequestDataError                = "ERR000283"
	GetNotificationsByTargetIDError                                  = "ERR000284"
	GetNotificationsByTargetIDSuccessMessage                         = "ERR000285"
	InvalidGetNotificationHistoriesByNotificationIDResponseDataError = "ERR000286"
	InvalidGetNotificationHistoriesByNotificationIDRequestDataError  = "ERR000287"
	GetNotificationHistoriesByNotificationIDError                    = "ERR000288"
	GetNotificationHistoriesByNotificationIDSuccessMessage           = "ERR000289"
	GetNotificatorError                                              = "ERR000290"
	InvalidRegisterOpenDirectoryResponse                             = "ERR000291"
	InvalidRegisterOpenDirectoryRequest                              = "ERR000292"
	InvalidRegisterOpenFileResponse                                  = "ERR000293"
	InvalidRegisterOpenFileRequest                                   = "ERR000294"
	OpenFolderError                                                  = "ERR000295"
	OpenFolderNotLocalAccountError                                   = "ERR000296"
	InvalidReloadRepositoriesResponse                                = "ERR000297"
	IDFError                                                         = "ERR000298"
	UpdateRepositoryAddressError                                     = "ERR000299"
	GetDnoteJSONDataError                                            = "ERR000300"
	InvalidUpdateDnoteJSONDataResponseDataError                      = "ERR000301"
	InvalidUpdateDnoteJSONDataRequestDataError                       = "ERR000302"
	DeleteUsersDnoteDataError                                        = "ERR000303"
	AddUsersDnoteDataError                                           = "ERR000304"
	AddKCError                                                       = "ERR000305"
	GetKCError                                                       = "ERR000306"
	AlreadyExistKCError                                              = "ERR000307"
	InvalidUpdateKCRequestDataError                                  = "ERR000308"
	InvalidUpdateKCResponseDataError                                 = "ERR000309"
	NotFoundKCError                                                  = "ERR000310"
	AccountInvalidAddKCResponseDataError                             = "ERR000311"
	AccountInvalidAddKCRequestDataError                              = "ERR000312"
	InvalidGetKCResponseDataError                                    = "ERR000313"
	InvalidGetKCRequestDataError                                     = "ERR000314"
	InvalidGetUpdatedDatasByTimeResponse                             = "ERR000315"
	InvalidGetUpdatedDatasByTimeRequest                              = "ERR000316"
	GetLatestDataRepositoryAddressByUpdateTimeAfterError             = "ERR000317"
	AccountInvalidCommitTxResponseDataError                          = "ERR000318"
	AccountInvalidCommitTxRequestDataError                           = "ERR000319"
	CommitTxGetKmemoError                                            = "ERR000320"
	CommitTxGetKCError                                               = "ERR000321"
	CommitTxGetIDFKyouError                                          = "ERR000322"
	CommitTxGetLantanaError                                          = "ERR000323"
	CommitTxGetMiError                                               = "ERR000324"
	CommitTxGetNlogError                                             = "ERR000325"
	CommitTxGetNotificationError                                     = "ERR000326"
	CommitTxGetReKyouError                                           = "ERR000327"
	CommitTxGetTagError                                              = "ERR000328"
	CommitTxGetTextError                                             = "ERR000329"
	CommitTxGetTimeIsError                                           = "ERR000330"
	CommitTxGetURLogError                                            = "ERR000331"
	AccountInvalidDiscardTxResponseDataError                         = "ERR000332"
	AccountInvalidDiscardTxRequestDataError                          = "ERR000333"
	CommitTxDeleteIDFKyouError                                       = "ERR000334"
	CommitTxDeleteKCError                                            = "ERR000335"
	CommitTxDeleteKmemoError                                         = "ERR000336"
	CommitTxDeleteLantanaError                                       = "ERR000337"
	CommitTxDeleteMiError                                            = "ERR000338"
	CommitTxDeleteNlogError                                          = "ERR000339"
	CommitTxDeleteNotificationError                                  = "ERR000340"
	CommitTxDeleteReKyouError                                        = "ERR000341"
	CommitTxDeleteTagError                                           = "ERR000342"
	CommitTxDeleteTextError                                          = "ERR000343"
	CommitTxDeleteTimeIsError                                        = "ERR000344"
	CommitTxDeleteURLogError                                         = "ERR000345"
	NotFoundTLSCertFileError                                         = "ERR000346"
	NotFoundTLSKeyFileError                                          = "ERR000347"
	GetAccountSessionsError                                          = "ERR000348"
	AddURLogLoginSessionError                                        = "ERR000349"
	InvalidSubmitKFTLTextRequestDataError                            = "ERR000350"
	SubmitKFTLTextError                                              = "ERR000351"
	InvalidGetKyousMCPRequestDataError                               = "ERR000352"
	InvalidGetKyousMCPResponseDataError                              = "ERR000353"
	GetKyousMCPError                                                 = "ERR000354"
	InvalidUpdateCacheRequestDataError                               = "ERR000355"
	InvalidUpdateCacheResponseDataError                              = "ERR000356"
	UpdateCacheError                                                 = "ERR000357"
	UpdateTagError                                                   = "ERR000360"
	UpdateTextError                                                  = "ERR000361"
	UpdateKmemoError                                                 = "ERR000362"
	UpdateURLogError                                                 = "ERR000363"
	UpdateNlogError                                                  = "ERR000364"
	UpdateTimeIsError                                                = "ERR000365"
	UpdateLantanaError                                               = "ERR000366"
	UpdateMiError                                                    = "ERR000367"
	UpdateReKyouError                                                = "ERR000368"
	UpdateIDFKyouError                                               = "ERR000369"
	UpdateKCError                                                    = "ERR000370"
	UpdateNotificationError                                          = "ERR000371"
	InvalidURLogBookmarkletRequestDataError                          = "ERR000372"
	AccountSessionExpiredError                                       = "ERR000373"
	LoginRateLimitError                                              = "ERR000374"
	InvalidBrowseZipContentsRequestDataError                         = "ERR000375"
	BrowseZipContentsError                                           = "ERR000376"
	InvalidGetPluginListRequestDataError                             = "ERR000377"
	GetPluginListError                                               = "ERR000378"
	InvalidGetPluginContentHTMLRequestDataError                      = "ERR000379"
	GetPluginContentHTMLError                                        = "ERR000380"
	InvalidGetPluginConfigHTMLRequestDataError                       = "ERR000381"
	GetPluginConfigHTMLError                                         = "ERR000382"
	InvalidPostPluginConfigRequestDataError                          = "ERR000383"
	PostPluginConfigError                                            = "ERR000384"
	InvalidGetIDFKyouByRelativePathRequestDataError                  = "ERR000385"
	GetIDFKyouByRelativePathError                                    = "ERR000386"
	InvalidAddMiReKyouRequestDataError                               = "ERR000390"
	InvalidAddMiReKyouResponseDataError                              = "ERR000391"
	AddMiReKyouError                                                 = "ERR000392"
	AlreadyExistMiReKyouError                                        = "ERR000393"
	InvalidUpdateMiReKyouRequestDataError                            = "ERR000394"
	InvalidUpdateMiReKyouResponseDataError                           = "ERR000395"
	UpdateMiReKyouError                                              = "ERR000396"
	NotFoundMiReKyouError                                            = "ERR000397"
	InvalidGetMiReKyouRequestDataError                               = "ERR000398"
	InvalidGetMiReKyouResponseDataError                              = "ERR000399"
	GetMiReKyouError                                                 = "ERR000400"
	CommitTxGetMiReKyouError                                         = "ERR000401"
	InvalidGetReKyousByTargetIDRequestDataError                      = "ERR000402"
	InvalidGetReKyousByTargetIDResponseDataError                     = "ERR000403"
	GetReKyousByTargetIDError                                        = "ERR000404"
	InvalidGetMiReKyousByTargetIDRequestDataError                    = "ERR000405"
	InvalidGetMiReKyousByTargetIDResponseDataError                   = "ERR000406"
	GetMiReKyousByTargetIDError                                      = "ERR000407"
	ExpiredPasswordResetTokenError                                   = "ERR000408"
	CannotDisableOwnAccountError                                     = "ERR000409"
	FindKyousError                                                   = "ERR000410"
	InvalidGetRepInfosMCPRequestDataError                            = "ERR000411"
	InvalidGetRepInfosMCPResponseDataError                           = "ERR000412"

	// TargetAccountNotFoundError は「操作対象のアカウントが存在しない」です。
	// AccountNotFoundError(ERR000002) と分けてあります。あちらは「自分のセッションに
	// 紐づくアカウントが消えている」で、クライアントの check_auth はそれを見て
	// ログイン画面へ飛ばします。管理者操作の対象が居ないだけで同じコードを返すと、
	// 存在しないユーザIDへパスワードリセットを実行した管理者が締め出されます。
	TargetAccountNotFoundError = "ERR000413"

	// LocalOnlyAccessDeniedError は IsLocalOnlyAccess が有効なサーバへ
	// ローカル以外から来たリクエストの拒否です(filterLocalOnly)。
	LocalOnlyAccessDeniedError = "ERR000414"

	// InternalServerPanicError は recoverMiddleware が panic を回収したときのものです。
	// panic 時はリクエストを読み直せないので、これだけは i18n を通さず固定文言で返します。
	InternalServerPanicError = "ERR000415"

	// SubmitKFTLTextInvalidInputError はメモ帳のテキスト自体が正しくないときのものです。
	// SubmitKFTLTextError(ERR000351) がサーバ側の失敗で 500 なのに対し、これは
	// 利用者の書き間違い（気分値が範囲外、終了する打刻が無い等）なので 400 です。
	// 2026-08-24 まで両者が同じ 500 に畳まれており、ステータスを見る層からは
	// 打ち間違いとサーバ障害が区別できませんでした。行ごとに1件ずつ立てます。
	SubmitKFTLTextInvalidInputError = "ERR000416"

	// RequestBodyTooLargeError は認証前のボディ先読み(readAuthBody、および
	// wrapNoAuthCapped の readBodyCapped)でリクエストボディが経路別上限を
	// 超えたときのものです。413 です。
	// 2026-08-24 まで本文なしの素の WriteHeader(413) を返しており、ステータスを見ずに
	// res.json() するクライアント(gkill-api.ts)側では本文が空のまま例外になっていました。
	RequestBodyTooLargeError = "ERR000417"

	// ReadRequestBodyError は認証系ミドルウェアの先読み(readAuthBody)での
	// リクエストボディ読み取り失敗(上限超過以外)です。サーバ側の失敗として 500 です。
	ReadRequestBodyError = "ERR000418"

	// CommitTxRolledBackError は /api/commit_tx の確定（temp rep → 実 rep の1つの SQLite トランザクション）が
	// 失敗して ROLLBACK されたときのものです。**実 rep には何も書かれていません**（temp rep の行は残ります）。
	// 2026-09-15 まで commit は種別ごとの逐次追記で、途中の種別で失敗すると書けた種別だけが残っていました
	// （部分確定）。500 です。documents/adr/0219-commit-tx-is-one-sqlite-transaction.md
	CommitTxRolledBackError = "ERR000419"

	// InvalidParseKFTLTextRequestDataError は /api/parse_kftl_text のリクエスト JSON が読めないときのものです。400 です。
	InvalidParseKFTLTextRequestDataError = "ERR000420"
	// ParseKFTLTextError は /api/parse_kftl_text の解析がサーバ側の理由で失敗したときのものです。
	// 利用者の書き間違いはエラーではなく応答の invalid_lines に載るので、ここに来るのは設定の取得失敗などです。500 です。
	ParseKFTLTextError = "ERR000421"

	// WriteRepMissingError はその種別の書き込み先 rep が未設定のまま追加・更新しようとしたときのものです。
	// 2026-09-15 まで tx を使わない add_* 経路は nil ポインタ参照で panic し「内部エラーが発生しました」に
	// なっていました（tx 経路は dao/reps/commit_tx.go の CommitTxWriteRepMissingError）。
	// 利用者が設定→保存先で直せる不備なので、ステータスは 500 のまま error_kind を config、
	// reason を write_rep_missing にしてあります（error_kind.go / error_reason.go）。
	WriteRepMissingError = "ERR000422"

	// SubmitKFTLTextIdempotencyKeyConflictError は /api/submit_kftl_text の再送キー（idempotency_key）が
	// 別の本文で使い回されたときのものです。再送キーは「成功した送信の再配送を1回に畳む」ためのもので、
	// サーバは成功した送信の本文の指紋（本文と create_app の SHA-256）と created[] を10分間控えています。
	// 同じキー・同じ本文なら元の created[] を replayed:true で返し、指紋が違えば何も書かずにこのコードで
	// 409 を返します。2026-09-19 までは本文を見ずに「成功・created は空」で返しており、保存されていない
	// 本文にも成功メッセージが返っていました（ADR-0510）。
	SubmitKFTLTextIdempotencyKeyConflictError = "ERR000423"

	// 以下はスキル（$GKILL_HOME/skills/<user_id>/<name>/ の SKILL.md と付属ファイル。ADR-0634）の API のものです。
	// 画面と MCP の両方が使います。応答の文言には dao/skills が返す補足（どのパスが悪いか等）を括弧で添えます。

	// InvalidGetSkillListRequestDataError は /api/get_skill_list のリクエスト JSON が読めないときのものです。400 です。
	InvalidGetSkillListRequestDataError = "ERR000424"
	// InvalidGetSkillRequestDataError は /api/get_skill のリクエスト JSON が読めないときのものです。400 です。
	InvalidGetSkillRequestDataError = "ERR000425"
	// InvalidDownloadSkillRequestDataError は /api/download_skill のリクエスト JSON が読めないときのものです。400 です。
	InvalidDownloadSkillRequestDataError = "ERR000426"
	// InvalidUploadSkillRequestDataError は /api/upload_skill のリクエスト JSON（または zip の base64）が読めないときのものです。400 です。
	InvalidUploadSkillRequestDataError = "ERR000427"
	// InvalidWriteSkillFileRequestDataError は /api/write_skill_file のリクエスト JSON が読めないときのものです。400 です。
	InvalidWriteSkillFileRequestDataError = "ERR000428"
	// InvalidDeleteSkillRequestDataError は /api/delete_skill のリクエスト JSON が読めないときのものです。400 です。
	InvalidDeleteSkillRequestDataError = "ERR000429"
	// SkillNotFoundError は指定の名前のスキルが無いときのものです。404 です。
	SkillNotFoundError = "ERR000430"
	// SkillFileNotFoundError はスキルの中に指定のファイルが無いときのものです。404 です。
	SkillFileNotFoundError = "ERR000431"
	// InvalidSkillNameError はスキル名が規則（英小文字・数字・ハイフン、1〜64文字）に合わないときのものです。400 です。
	InvalidSkillNameError = "ERR000432"
	// InvalidSkillFilePathError はスキル内のパスが規則に合わない・既存のファイルと大文字小文字だけ違う等のときのものです。400 です。
	InvalidSkillFilePathError = "ERR000433"
	// InvalidSkillManifestError は SKILL.md の frontmatter（name と description）が読めない・不正なときのものです。400 です。
	InvalidSkillManifestError = "ERR000434"
	// InvalidSkillZipError はアップロードされた zip がスキルとして取り込めない（SKILL.md が無い、
	// 使えない名前・".."・シンボリックリンクがある等）ときのものです。400 です。
	InvalidSkillZipError = "ERR000435"
	// SkillFileAlreadyExistsError は revision を渡さずに（新規作成のつもりで）既にあるファイルへ書こうとしたときのものです。409 です。
	SkillFileAlreadyExistsError = "ERR000436"
	// SkillRevisionConflictError は渡された revision が今の中身と食い違う（読んだ後に書き換えられた）ときのものです。409 です。
	SkillRevisionConflictError = "ERR000437"
	// SkillManifestDeleteError は SKILL.md だけを消そうとしたときのものです。消すならスキルごと消します。400 です。
	SkillManifestDeleteError = "ERR000438"
	// GetSkillListError はスキル一覧の取得がサーバ側の理由（ディスク等）で失敗したときのものです。500 です。
	GetSkillListError = "ERR000439"
	// GetSkillError はスキル・スキル内ファイルの取得がサーバ側の理由で失敗したときのものです。500 です。
	GetSkillError = "ERR000440"
	// DownloadSkillError はスキルの zip の作成がサーバ側の理由で失敗したときのものです。500 です。
	DownloadSkillError = "ERR000441"
	// UploadSkillError はスキルの zip での置き換えがサーバ側の理由（ファイルを開いている等）で失敗したときのものです。
	// 既存のスキルは元のまま残ります。500 です。
	UploadSkillError = "ERR000442"
	// WriteSkillFileError はスキル内ファイルの書き込みがサーバ側の理由で失敗したときのものです。500 です。
	WriteSkillFileError = "ERR000443"
	// DeleteSkillError はスキル・スキル内ファイルの削除がサーバ側の理由で失敗したときのものです。500 です。
	DeleteSkillError = "ERR000444"
)
